/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bon;

import developer.Task;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import po.ProductBacklog;

/**
 *
 * @author yonay
 */
public class CambiarRol extends javax.swing.JFrame {

    /**
     * Creates new form CambiarRol
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    private String develop;
    private String password;
    private String type;
    String[] deve;
    private boolean isSm=false;

    public CambiarRol() {
        initComponents();
    }
    public CambiarRol(String dev){
        develop=dev;
        initComponents();
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from login");
            deve=develop.split(" ");
            
                while(rs.next()){
                    if(rs.getString("name").equals(deve[0])){
                        password=rs.getString("password");
                        type=rs.getString("type");
                    }
                    if(rs.getString("type").equals("scrumMaster")){
                        isSm=true;
                    }
                    
                }
                name.setText(develop);
            
            
        }catch(Exception e){
            System.out.println("Error al acceder a db");
        }
        System.out.println(type);
        System.out.println(password);
        System.out.println(deve[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambiarRolTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cambiarRolPassToEdit = new javax.swing.JLabel();
        passCambiarRol = new javax.swing.JPasswordField();
        despedirCambiarRol = new javax.swing.JButton();
        degradarCambiarRol = new javax.swing.JButton();
        ascenderCambiarRol = new javax.swing.JButton();
        canCambiarRol = new javax.swing.JButton();
        name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        getContentPane().setLayout(new java.awt.GridLayout(8, 0));

        cambiarRolTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cambiarRolTitle.setText("Cambiar Rol");
        getContentPane().add(cambiarRolTitle);

        cambiarRolPassToEdit.setText("Contraseña admin");
        jPanel1.add(cambiarRolPassToEdit);

        passCambiarRol.setMinimumSize(new java.awt.Dimension(600, 20));
        passCambiarRol.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(passCambiarRol);

        getContentPane().add(jPanel1);

        despedirCambiarRol.setText("Despedir");
        despedirCambiarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirCambiarRolActionPerformed(evt);
            }
        });
        getContentPane().add(despedirCambiarRol);

        degradarCambiarRol.setText("Degradar");
        degradarCambiarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degradarCambiarRolActionPerformed(evt);
            }
        });
        getContentPane().add(degradarCambiarRol);

        ascenderCambiarRol.setText("Ascender");
        ascenderCambiarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascenderCambiarRolActionPerformed(evt);
            }
        });
        getContentPane().add(ascenderCambiarRol);

        canCambiarRol.setText("Cancelar");
        canCambiarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canCambiarRolActionPerformed(evt);
            }
        });
        getContentPane().add(canCambiarRol);

        name.setText("jLabel1");
        getContentPane().add(name);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canCambiarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canCambiarRolActionPerformed
        // TODO add your handling code here:
        Personal personal = new Personal();
        personal.setLocationRelativeTo(null);
        personal.setVisible(true);
        dispose();
    }//GEN-LAST:event_canCambiarRolActionPerformed

    private void despedirCambiarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirCambiarRolActionPerformed
        // TODO add your handling code here:
        if(String.valueOf(passCambiarRol.getPassword()).equals("1234")){
            int respuesta=JOptionPane.showConfirmDialog(null, "¿Estas seguro que quieres despedir a esta persona?");
            if(respuesta==0){
                      
            
                try{
                    String query = "DELETE FROM login WHERE name = ?";

                PreparedStatement preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, deve[0]);
                preparedStmt.execute();
                }catch(SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, e);
                }
                Personal pr = new Personal();
                pr.setLocationRelativeTo(null);
                pr.setVisible(true);
                dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Introduzca la contraseña de admin correctamente");
        }
        
    }//GEN-LAST:event_despedirCambiarRolActionPerformed

    private void degradarCambiarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degradarCambiarRolActionPerformed
        // TODO add your handling code here:
        if(String.valueOf(passCambiarRol.getPassword()).equals("1234")){
            if(type.equals("scrumMaster")){
                try {

                    String sql = "UPDATE login set password='"+password+"',type='"
                    +"developer"+"' where name='"
                    +deve[0]+"'";
                PreparedStatement pst=connection.prepareStatement(sql);
                pst.execute();

                } catch (SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, e);
                }
                Personal pr = new Personal();
                pr.setLocationRelativeTo(null);
                pr.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "No puedes degradar a un developer");
                CambiarRol cambiarRol = new CambiarRol(develop);
                cambiarRol.setLocationRelativeTo(null);
                cambiarRol.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Introduzca la contraseña de admin correctamente");
            CambiarRol cambiarRol = new CambiarRol(develop);
            cambiarRol.setLocationRelativeTo(null);
            cambiarRol.setVisible(true);
        }
    }//GEN-LAST:event_degradarCambiarRolActionPerformed

    private void ascenderCambiarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascenderCambiarRolActionPerformed
        // TODO add your handling code here:
        System.out.println(type);
        if(String.valueOf(passCambiarRol.getPassword()).equals("1234")){
            if(isSm== true){
                JOptionPane.showMessageDialog(null, "Ya hay un scrumMaster Registrado");
                CambiarRol cambiarRol = new CambiarRol(develop);
                cambiarRol.setLocationRelativeTo(null);
                cambiarRol.setVisible(true);
                dispose();
            }else if(type.equals("developer")){
                try {

                    String sql = "UPDATE login set password='"+password+"',type='"
                    +"scrumMaster"+"' where name='"
                    +deve[0]+"'";
                PreparedStatement pst=connection.prepareStatement(sql);
                pst.execute();

                } catch (SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, e);
                }
                Personal pr = new Personal();
                pr.setLocationRelativeTo(null);
                pr.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "No puedes ascender a un scrumMaster");
                CambiarRol cambiarRol = new CambiarRol(develop);
                cambiarRol.setLocationRelativeTo(null);
                cambiarRol.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Introduzca la contraseña de admin correctamente");
            CambiarRol cambiarRol = new CambiarRol(develop);
            cambiarRol.setLocationRelativeTo(null);
            cambiarRol.setVisible(true);
        }
    }//GEN-LAST:event_ascenderCambiarRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarRol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ascenderCambiarRol;
    private javax.swing.JLabel cambiarRolPassToEdit;
    private javax.swing.JLabel cambiarRolTitle;
    private javax.swing.JButton canCambiarRol;
    private javax.swing.JButton degradarCambiarRol;
    private javax.swing.JButton despedirCambiarRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField passCambiarRol;
    // End of variables declaration//GEN-END:variables
}
