/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bon;

import developer.Developer;
import po.ProductOwner;
import scm.ScrumMaster;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form hiato
     */
    
    BD bd = new BD();
    Connection connection = bd.conexion();
    public Login() {
        initComponents();
    }
    void clean(){
        passLogin.setText("");
        userLogin.setText("");
    }
    
    void access(String usuario,String password){
        
        String develop="";
        String pd="";
        String scm="";
        
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from login");
            boolean success = false;
            while(rs.next()){
                
                develop="developer";
                pd="productOwner";
                scm="scrumMaster";             
                if(usuario.equals(rs.getString("name")) && password.equals(rs.getString("password")) && develop.equals(rs.getString("type"))){
                    Developer developer = new Developer(rs.getString("name"));
                    developer.setLocationRelativeTo(null);
                    developer.setVisible(true);
                    success = true;
                    dispose();
                }else if(usuario.equals(rs.getString("name")) && password.equals(rs.getString("password")) && pd.equals(rs.getString("type"))){
                    ProductOwner productOwner = new ProductOwner(rs.getString("name"));
                    productOwner.setLocationRelativeTo(null);
                    productOwner.setVisible(true);
                    success = true;
                    dispose();
                }else if(usuario.equals(rs.getString("name")) && password.equals(rs.getString("password")) && scm.equals(rs.getString("type"))){
                    ScrumMaster scrumMaster = new ScrumMaster(rs.getString("name"));
                    scrumMaster.setLocationRelativeTo(null);
                    scrumMaster.setVisible(true);
                    success = true;
                    dispose();
                }
            }
            if (!success) {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto.");
            }
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTitle = new javax.swing.JLabel();
        personalLogin = new javax.swing.JButton();
        loginUser = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        loginPass = new javax.swing.JLabel();
        passLogin = new javax.swing.JPasswordField();
        accLogin = new javax.swing.JButton();
        registerLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        loginTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginTitle.setText("Login");
        getContentPane().add(loginTitle);

        personalLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bon/rsz_user_male2-512.png"))); // NOI18N
        personalLogin.setText("");
        personalLogin.setPreferredSize(new java.awt.Dimension(5, 3));
        personalLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalLoginActionPerformed(evt);
            }
        });
        getContentPane().add(personalLogin);

        loginUser.setText("Usuario");
        getContentPane().add(loginUser);
        getContentPane().add(userLogin);

        loginPass.setText("Contraseña");
        getContentPane().add(loginPass);
        getContentPane().add(passLogin);

        accLogin.setText("Aceptar");
        accLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accLoginActionPerformed(evt);
            }
        });
        getContentPane().add(accLogin);

        registerLogin.setText("Registrarse");
        registerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerLoginActionPerformed(evt);
            }
        });
        getContentPane().add(registerLogin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accLoginActionPerformed
        // TODO add your handling code here:
        String usuario=userLogin.getText();
        String pass = String.valueOf(passLogin.getPassword());
        access(usuario, pass);
    }//GEN-LAST:event_accLoginActionPerformed

    private void registerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLoginActionPerformed
        // TODO add your handling code here:
        Register register = new Register();
        register.setLocationRelativeTo(null);
        register.setVisible(true);
        dispose();
    }//GEN-LAST:event_registerLoginActionPerformed

    private void personalLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalLoginActionPerformed
        // TODO add your handling code here:
        Personal personal = new Personal();
        personal.setLocationRelativeTo(null);
        personal.setVisible(true);
        dispose();
    }//GEN-LAST:event_personalLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
                login.setLocationRelativeTo(null);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accLogin;
    private javax.swing.JLabel loginPass;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel loginUser;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JButton personalLogin;
    private javax.swing.JButton registerLogin;
    private javax.swing.JTextField userLogin;
    // End of variables declaration//GEN-END:variables
}
