/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bon;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import po.ProductOwner;

/**
 *
 * @author yonay
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    private boolean isSm=false;
    private boolean isPo=false;
    private int deve=0;
    private int scr=0;
    private int po=0;
    public Register() {
        initComponents();
        selectionRolRegister.add("developer");
        selectionRolRegister.add("productOwner");
        selectionRolRegister.add("scrumMaster");
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from login");
            
                while(rs.next()){
                    if(rs.getString("type").equals("scrumMaster")){
                        isSm=true;
                        scr+=1;
                    }
                    if(rs.getString("type").equals("productOwner")){
                        isSm=true;
                        po+=1;
                    }
                    if(rs.getString("type").equals("developer")){
                        deve+=1;
                    }    
                    
                    
                }
            jLabel1.setText("<Html>Hay "+deve+"desarroladores.<br>Hay "+scr+" scrumMasters.<br> Hay "+po+" productOwner.</Html>");
            
        }catch(Exception e){
            System.out.println("Error al acceder a db");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerTitle = new javax.swing.JLabel();
        registerUser = new javax.swing.JLabel();
        registerPass = new javax.swing.JLabel();
        registerType = new javax.swing.JLabel();
        userRegister = new javax.swing.JTextField();
        passRegister = new javax.swing.JPasswordField();
        registerPassToRegister = new javax.swing.JLabel();
        passToRegister = new javax.swing.JPasswordField();
        accRegister = new javax.swing.JButton();
        canRegister = new javax.swing.JButton();
        selectionRolRegister = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");

        registerTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        registerTitle.setText("Registro");

        registerUser.setText("Usuario");

        registerPass.setText("Contraseña");

        registerType.setText("Tipo de usuario");

        registerPassToRegister.setText("Contraseña de registro");

        accRegister.setText("Registrar");
        accRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accRegisterActionPerformed(evt);
            }
        });

        canRegister.setText("Cancelar");
        canRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canRegisterActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("6 o más caracteres");

        jLabel3.setText("6 o más caracteres");

        jLabel4.setText("*1234*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerPassToRegister)
                            .addComponent(registerPass)
                            .addComponent(registerUser)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(accRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passToRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(passRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(userRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(selectionRolRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(canRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(registerTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUser)
                    .addComponent(userRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPass)
                    .addComponent(passRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPassToRegister)
                    .addComponent(passToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectionRolRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accRegister)
                            .addComponent(canRegister)))
                    .addComponent(registerType))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canRegisterActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_canRegisterActionPerformed

    private void accRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accRegisterActionPerformed
        // TODO add your handling code here:
      
        if(String.valueOf(passToRegister.getPassword()).equals("1234")){
            if(String.valueOf(passRegister.getPassword()).length() > 5){
                if(isSm== true && selectionRolRegister.getSelectedItem().equals("scrumMaster")){
                    JOptionPane.showMessageDialog(null, "Ya hay un scrumMaster Registrado");
                    Register register = new Register();
                    register.setLocationRelativeTo(null);
                    register.setVisible(true);
                    dispose(); 
                }else if(isPo= true && selectionRolRegister.getSelectedItem().equals("productOwner")){
                    JOptionPane.showMessageDialog(null, "Ya hay un productOwner Registrado");
                    Register register = new Register();
                    register.setLocationRelativeTo(null);
                    register.setVisible(true);
                    dispose();
                }else{
                        try{
                            String choice = selectionRolRegister.getSelectedItem();

                            String query = " insert into login (name, password, type)"
                            + " values (?, ?, ?)";

                  // create the mysql insert preparedstatement
                            PreparedStatement preparedStmt = connection.prepareStatement(query);
                            preparedStmt.setString(1, userRegister.getText());
                            preparedStmt.setString(2, String.valueOf(passRegister.getPassword()));
                            preparedStmt.setString(3, choice);

                  // execute the preparedstatement
                            preparedStmt.execute();
                            JOptionPane.showMessageDialog(null, "Se ha registrado correctamente como: "+userRegister.getText());
                            Login log = new Login();
                            log.setLocationRelativeTo(null);
                            log.setVisible(true);
                            dispose();
                        }catch(SQLException | HeadlessException e){
                            JOptionPane.showMessageDialog(null, "Ese usuario ya existe, pruebe otro.");
                            Register register = new Register();
                            register.setLocationRelativeTo(null);
                            register.setVisible(true);
                            dispose();
                        }
                    
                   
                }
                
            }else{
                JOptionPane.showMessageDialog(null, 
                        "Contraseña no válida.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
                Register register = new Register();
                register.setLocationRelativeTo(null);
                register.setVisible(true);
                dispose();
            }
        }else{
            
        }
    }//GEN-LAST:event_accRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accRegister;
    private javax.swing.JButton canRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passRegister;
    private javax.swing.JPasswordField passToRegister;
    private javax.swing.JLabel registerPass;
    private javax.swing.JLabel registerPassToRegister;
    private javax.swing.JLabel registerTitle;
    private javax.swing.JLabel registerType;
    private javax.swing.JLabel registerUser;
    private java.awt.Choice selectionRolRegister;
    private javax.swing.JTextField userRegister;
    // End of variables declaration//GEN-END:variables
}
