/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po;

import bon.BD;
import developer.Identificador;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class AddTask extends javax.swing.JFrame {

    /**
     * Creates new form AddTask
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    private String proj;
    private int id;
    private Identificador identificador;
    public AddTask() {
        initComponents();
    }
    public AddTask(String project){
        proj=project;
        initComponents();
        priorityRulesAddTask.setText("<html>0 - Sin prioridad <br> 1 - Poca prioridad <br> 5 - Máxima prioridad</html>");
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from task");
            while(rs.next()){
                id=Integer.parseInt(rs.getString("id"));
            }
            identificador = new Identificador(id);
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addTaskName = new javax.swing.JLabel();
        nameAddTask = new javax.swing.JTextField();
        addTaskPriority = new javax.swing.JLabel();
        priorityAddTask = new javax.swing.JTextField();
        addTaskDescription = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        descriptionAddTask = new javax.swing.JTextArea();
        accAddTask = new javax.swing.JButton();
        canAddTask = new javax.swing.JButton();
        priorityRulesAddTask = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");

        addTaskName.setText("Nombre de la Tarea");

        addTaskPriority.setText("Prioridad (0-5)");

        priorityAddTask.setText("0");

        addTaskDescription.setText("Descripción");

        descriptionAddTask.setColumns(20);
        descriptionAddTask.setRows(5);
        scroll.setViewportView(descriptionAddTask);

        accAddTask.setText("Añadir");
        accAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accAddTaskActionPerformed(evt);
            }
        });

        canAddTask.setText("Cancel");
        canAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canAddTaskActionPerformed(evt);
            }
        });

        priorityRulesAddTask.setText("0 -Sin prioridad ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTaskName)
                    .addComponent(nameAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTaskDescription)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTaskPriority)
                    .addComponent(priorityAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityRulesAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTaskName)
                    .addComponent(addTaskPriority))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityRulesAddTask))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canAddTask)
                    .addComponent(accAddTask))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canAddTaskActionPerformed
        // TODO add your handling code here:
        ProductBacklog pr = new ProductBacklog(proj);
        pr.setLocationRelativeTo(null);
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_canAddTaskActionPerformed
private int getPriority(){
    return Integer.parseInt(priorityAddTask.getText());
}
    private void accAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accAddTaskActionPerformed
        // TODO add your handling code here:
        if(nameAddTask.getText().equals("") || descriptionAddTask.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Se tiene que indicar un nombre y una descripción.");
        }else if(getPriority() > 5 || getPriority() < 0 ){
            JOptionPane.showMessageDialog(null, "Introduzca una prioridad válida");                      
        }else{
            try{
                String query = " insert into task (id, Projects, name, duration, priority, description, state, hours, develop, sprint)"
                + " values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = connection.prepareStatement(query);
                preparedStmt.setInt(1, identificador.getId());
                preparedStmt.setString(2, proj);
                preparedStmt.setString(3, nameAddTask.getText());
                preparedStmt.setInt(4, 0);
                preparedStmt.setInt(5, Integer.parseInt(priorityAddTask.getText()));
                preparedStmt.setString(6, descriptionAddTask.getText());
                preparedStmt.setInt(7, 0);
                preparedStmt.setInt(8, 0);
                preparedStmt.setString(9, "");
                preparedStmt.setInt(10,0);
                // execute the preparedstatement
                preparedStmt.execute();
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);
            }
            ProductBacklog pr = new ProductBacklog(proj);
            pr.setLocationRelativeTo(null);
            pr.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_accAddTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accAddTask;
    private javax.swing.JLabel addTaskDescription;
    private javax.swing.JLabel addTaskName;
    private javax.swing.JLabel addTaskPriority;
    private javax.swing.JButton canAddTask;
    private javax.swing.JTextArea descriptionAddTask;
    private javax.swing.JTextField nameAddTask;
    private javax.swing.JTextField priorityAddTask;
    private javax.swing.JLabel priorityRulesAddTask;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
