/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po;

import po.ProductOwner;
import bon.BD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class CreateProject extends javax.swing.JFrame {

    /**
     * Creates new form CreateProject
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    public CreateProject() {      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProjectName = new javax.swing.JLabel();
        createProjectDescription = new javax.swing.JLabel();
        nameCreateProject = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        descriptionCreateProject = new javax.swing.JTextArea();
        accCreateProject = new javax.swing.JButton();
        canCreateProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Owner - Crear proyecto");

        createProjectName.setText("Nombre del Proyecto");

        createProjectDescription.setText("Descripción");

        descriptionCreateProject.setColumns(20);
        descriptionCreateProject.setRows(5);
        scroll.setViewportView(descriptionCreateProject);

        accCreateProject.setText("Crear");
        accCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accCreateProjectActionPerformed(evt);
            }
        });

        canCreateProject.setText("Cancelar");
        canCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canCreateProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createProjectDescription)
                    .addComponent(nameCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createProjectName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(canCreateProject)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(scroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(createProjectName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createProjectDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canCreateProject)
                    .addComponent(accCreateProject))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accCreateProjectActionPerformed
        // TODO add your handling code here:
        if(nameCreateProject.getText().equals("") || descriptionCreateProject.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Se deben rellenar todos los campos.");
        }else{
            try{
                String query = " insert into projects (name, Duration, Description)"
                + " values (?, ?, ?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, nameCreateProject.getText());
                preparedStmt.setInt(2, 0);
                preparedStmt.setString(3, descriptionCreateProject.getText());

                // execute the preparedstatement
                preparedStmt.execute();

            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);
            }
            ProductOwner pr = new ProductOwner();
            pr.setLocationRelativeTo(null);
            pr.setVisible(true);
            dispose();
        
        }
    }//GEN-LAST:event_accCreateProjectActionPerformed

    private void canCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canCreateProjectActionPerformed
        // TODO add your handling code here:
        ProductOwner pr = new ProductOwner();
        pr.setLocationRelativeTo(null);
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_canCreateProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accCreateProject;
    private javax.swing.JButton canCreateProject;
    private javax.swing.JLabel createProjectDescription;
    private javax.swing.JLabel createProjectName;
    private javax.swing.JTextArea descriptionCreateProject;
    private javax.swing.JTextField nameCreateProject;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
