/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po;

import bon.BD;
import developer.Task;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class ModifyTask extends javax.swing.JFrame {

    /**
     * Creates new form ModifyTask
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    private String proj;
    private String task2;
    private String duration;
    private String state;
    private String hours;
    private String develop;
    private String id;
    private String idSprint;
    private String developer;

    public ModifyTask() {
        initComponents();
    }

    public ModifyTask(String proyect, String task,String deve) {
        initComponents();
        developer=deve;
 
        task2 = task;
        proj = proyect;
        jLabel2.setText("<Html>"+proj +"/ModifyTask</Html>");
        jComboBox1.addItem("0 - Sin prioridad");
        jComboBox1.addItem("1 - Poca prioridad");
        jComboBox1.addItem("2 - Prioridad media");
        jComboBox1.addItem("3 - Alta prioridad");
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from task");

            while (rs.next()) {

                if (rs.getString("name").equals(task2) && rs.getString("Projects").equals(proj)) {
                    taskNameModify.setText(rs.getString("name"));
                    jComboBox1.setSelectedIndex(Integer.parseInt(rs.getString("priority")));
                    descriptionModify.setText(rs.getString("description"));
                    duration = rs.getString("duration");
                    state = rs.getString("state");
                    hours = rs.getString("hours");
                    develop = rs.getString("develop");
                    id = rs.getString("id");
                    idSprint = rs.getString("sprint");
                }
            }

        } catch (SQLException e) {
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifyTaskName = new javax.swing.JLabel();
        modifyTaskPriority = new javax.swing.JLabel();
        taskNameModify = new javax.swing.JTextField();
        modifyTaskDescription = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        descriptionModify = new javax.swing.JTextArea();
        accModifyTask = new javax.swing.JButton();
        canModifyTask = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        setResizable(false);

        modifyTaskName.setText("Nombre de la Tarea");

        modifyTaskPriority.setText("Prioridad");

        modifyTaskDescription.setText("Descripción");

        descriptionModify.setColumns(20);
        descriptionModify.setRows(5);
        scroll.setViewportView(descriptionModify);

        accModifyTask.setText("Modificar");
        accModifyTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accModifyTaskActionPerformed(evt);
            }
        });

        canModifyTask.setText("Cancelar");
        canModifyTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canModifyTaskActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskNameModify, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyTaskName)
                            .addComponent(modifyTaskDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyTaskPriority)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scroll)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(canModifyTask)
                                .addGap(18, 18, 18)
                                .addComponent(accModifyTask)))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyTaskName)
                    .addComponent(modifyTaskPriority))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNameModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modifyTaskDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canModifyTask)
                    .addComponent(accModifyTask))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int getPriority() {
        return jComboBox1.getSelectedIndex();
    }
    private void accModifyTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accModifyTaskActionPerformed
        // TODO add your handling code here:
        if (taskNameModify.getText().equals("") || descriptionModify.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Se tiene que indicar un nombre y una descripción.");
        } else if (getPriority() > 5 || getPriority() < 0) {
            JOptionPane.showMessageDialog(null, "Introduzca una prioridad válida");
        } else {
            try {
                String sql = "UPDATE task set Projects='" + proj + "',name='"
                        + taskNameModify.getText() + "',duration='" + duration + "',priority='"
                        + getPriority() + "',description='"
                        + descriptionModify.getText() + "',state='"
                        + state + "',hours='"
                        + hours + "',develop='"
                        + develop + "',sprint='"
                        + idSprint + "' where id='"
                        + id + "'";
                PreparedStatement pst = connection.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Se ha modificado la tarea "+taskNameModify.getText()+" con éxito");

            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            ProductBacklog pr = new ProductBacklog(proj,developer);
            pr.setLocationRelativeTo(null);
            pr.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_accModifyTaskActionPerformed

    private void canModifyTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canModifyTaskActionPerformed
        // TODO add your handling code here:
        ProductBacklog pr = new ProductBacklog(proj,developer);
        pr.setLocationRelativeTo(null);
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_canModifyTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accModifyTask;
    private javax.swing.JButton canModifyTask;
    private javax.swing.JTextArea descriptionModify;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel modifyTaskDescription;
    private javax.swing.JLabel modifyTaskName;
    private javax.swing.JLabel modifyTaskPriority;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField taskNameModify;
    // End of variables declaration//GEN-END:variables
}
