/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po;

import bon.BD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class ProductBacklog extends javax.swing.JFrame {

    /**
     * Creates new form productBacklog
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    String proy;
    
    List<String> tareas = new ArrayList<>();
    public ProductBacklog() {
        initComponents();
    }
    public ProductBacklog(String project){
        proy= project;
        initComponents();
        productBacklogProject.setText(proy);
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from task");
            
            while(rs.next()){
                
                if(rs.getString("Projects").equals(proy)){
                    tareas.add(rs.getString("name"));
                }
            }
            if(tareas.size()>0){
                String[] mylist = new String[tareas.size()];
                mylist = tareas.toArray(mylist);
                tasksProductBacklog.setListData(mylist);
            }
            
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productBacklogProject = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tasksProductBacklog = new javax.swing.JList<>();
        addProductBacklog = new javax.swing.JButton();
        modProductBacklog = new javax.swing.JButton();
        remProductBacklog = new javax.swing.JButton();
        canProductBacklog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Owner - Modificar backlog");

        productBacklogProject.setText("Proyecto Actual");

        scroll.setViewportView(tasksProductBacklog);

        addProductBacklog.setText("Añadir Tarea");
        addProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBacklogActionPerformed(evt);
            }
        });

        modProductBacklog.setText("Modificar Tarea");
        modProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modProductBacklogActionPerformed(evt);
            }
        });

        remProductBacklog.setText("Eliminar Tarea");
        remProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remProductBacklogActionPerformed(evt);
            }
        });

        canProductBacklog.setText("Cancelar");
        canProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canProductBacklogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(remProductBacklog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addProductBacklog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modProductBacklog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(productBacklogProject))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(canProductBacklog)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(productBacklogProject)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProductBacklog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modProductBacklog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(remProductBacklog))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(canProductBacklog)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modProductBacklogActionPerformed
        // TODO add your handling code here:
        String task =tasksProductBacklog.getSelectedValue();
        if(!(task == null)){
            ModifyTask m = new ModifyTask(proy,task);
            m.setLocationRelativeTo(null);
            m.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una tarea.");
        }
    }//GEN-LAST:event_modProductBacklogActionPerformed

    private void canProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canProductBacklogActionPerformed
        // TODO add your handling code here:
        ProductOwner po = new ProductOwner();
        po.setLocationRelativeTo(null);
        po.setVisible(true);
        dispose();
    }//GEN-LAST:event_canProductBacklogActionPerformed

    private void remProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remProductBacklogActionPerformed
        // TODO add your handling code here:
        if(!(tasksProductBacklog.getSelectedValue() == null)){
            try{
                String query = "DELETE FROM task WHERE name = ?";

            PreparedStatement preparedStmt = connection.prepareStatement(query);
            preparedStmt.setString(1, tasksProductBacklog.getSelectedValue());
            preparedStmt.execute();
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, e);
            }
            ProductBacklog pr = new ProductBacklog(proy);
            pr.setLocationRelativeTo(null);
            pr.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una tarea para borrar.");
        }
    }//GEN-LAST:event_remProductBacklogActionPerformed

    private void addProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBacklogActionPerformed
        // TODO add your handling code here:
        AddTask addtask = new AddTask(proy);
        addtask.setLocationRelativeTo(null);
        addtask.setVisible(true);
        dispose();
    }//GEN-LAST:event_addProductBacklogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductBacklog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductBacklog;
    private javax.swing.JButton canProductBacklog;
    private javax.swing.JButton modProductBacklog;
    private javax.swing.JLabel productBacklogProject;
    private javax.swing.JButton remProductBacklog;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JList<String> tasksProductBacklog;
    // End of variables declaration//GEN-END:variables
}
