/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po;

import bon.BD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class ProductBacklog extends javax.swing.JFrame {

    /**
     * Creates new form productBacklog
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    String proy;
    private String develop;
    
    List<String> tareas = new ArrayList<>();
    public ProductBacklog() {
        initComponents();
    }
    public ProductBacklog(String project,String deve){
        proy= project;
        develop=deve;
        initComponents();
        productBacklogProject.setText("<Html> Proyecto: "+proy +"<br> Ventana: ProductBacklog</Html>");
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from task");
            
            while(rs.next()){
                
                if(rs.getString("Projects").equals(proy)){
                    tareas.add(rs.getString("name"));
                }
            }
            if(tareas.size()>0){
                String[] mylist = new String[tareas.size()];
                mylist = tareas.toArray(mylist);
                tasksProductBacklog.setListData(mylist);
            }
            
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        productBacklogProject = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tasksProductBacklog = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        addProductBacklog = new javax.swing.JButton();
        modProductBacklog = new javax.swing.JButton();
        remProductBacklog = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        canProductBacklog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        productBacklogProject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productBacklogProject.setText("Proyecto Actual");
        getContentPane().add(productBacklogProject);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        scroll.setViewportView(tasksProductBacklog);

        jPanel1.add(scroll);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        addProductBacklog.setText("Añadir Tarea");
        addProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBacklogActionPerformed(evt);
            }
        });
        jPanel2.add(addProductBacklog);

        modProductBacklog.setText("Modificar Tarea");
        modProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modProductBacklogActionPerformed(evt);
            }
        });
        jPanel2.add(modProductBacklog);

        remProductBacklog.setText("Eliminar Tarea");
        remProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remProductBacklogActionPerformed(evt);
            }
        });
        jPanel2.add(remProductBacklog);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        canProductBacklog.setText("Cancelar");
        canProductBacklog.setPreferredSize(new java.awt.Dimension(60, 10));
        canProductBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canProductBacklogActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 394;
        gridBagConstraints.ipady = 77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 17, 0);
        jPanel3.add(canProductBacklog, gridBagConstraints);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modProductBacklogActionPerformed
        // TODO add your handling code here:
        String task =tasksProductBacklog.getSelectedValue();
        if(!(task == null)){
            ModifyTask m = new ModifyTask(proy,task,develop);
            m.setLocationRelativeTo(null);
            m.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una tarea.");
        }
    }//GEN-LAST:event_modProductBacklogActionPerformed

    private void canProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canProductBacklogActionPerformed
        // TODO add your handling code here:
        ProductOwner po = new ProductOwner(develop);
        po.setLocationRelativeTo(null);
        po.setVisible(true);
        dispose();
    }//GEN-LAST:event_canProductBacklogActionPerformed

    private void remProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remProductBacklogActionPerformed
        // TODO add your handling code here:
        if(!(tasksProductBacklog.getSelectedValue() == null)){
            int respuesta=JOptionPane.showConfirmDialog(null, "¿Estas seguro que quieres eliminar esta tarea?");
            if(respuesta==0){
                try{
                    String query = "DELETE FROM task WHERE name = ?";

                PreparedStatement preparedStmt = connection.prepareStatement(query);
                preparedStmt.setString(1, tasksProductBacklog.getSelectedValue());
                preparedStmt.execute();
                }catch(SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, e);
                }
                ProductBacklog pr = new ProductBacklog(proy,develop);
                pr.setLocationRelativeTo(null);
                pr.setVisible(true);
                dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una tarea para borrar.");
        }
    }//GEN-LAST:event_remProductBacklogActionPerformed

    private void addProductBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBacklogActionPerformed
        // TODO add your handling code here:
        AddTask addtask = new AddTask(proy,develop);
        addtask.setLocationRelativeTo(null);
        addtask.setVisible(true);
        dispose();
    }//GEN-LAST:event_addProductBacklogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductBacklog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductBacklog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductBacklog;
    private javax.swing.JButton canProductBacklog;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton modProductBacklog;
    private javax.swing.JLabel productBacklogProject;
    private javax.swing.JButton remProductBacklog;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JList<String> tasksProductBacklog;
    // End of variables declaration//GEN-END:variables
}
