/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scm;

import bon.BD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class AddGastos extends javax.swing.JFrame {

    /**
     * Creates new form AddGastos
     */
    private String project;
    BD bd = new BD();
    Connection connection = bd.conexion();
    private String developer;
    private int id;
    private IdentificadorGastos identificador;

    public AddGastos() {
        initComponents();
    }

    public AddGastos(String proy, String dev) {
        developer = dev;
        project = proy;
        initComponents();
        jLabel1.setText("<Html> Proyecto Actual: "+project+"<br> Ventana Actual: Añadir Gastos</Html>");
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from gasto");
            while (rs.next()) {
                id = Integer.parseInt(rs.getString("id"));
            }
            identificador = new IdentificadorGastos(id);
        } catch (SQLException e) {
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        descriptionAddGastos = new javax.swing.JTextArea();
        accAddGastos = new javax.swing.JButton();
        canAddGastos = new javax.swing.JButton();
        addGastosName = new javax.swing.JLabel();
        addGastosDescription = new javax.swing.JLabel();
        addGastosUnidad = new javax.swing.JLabel();
        addGastosPrecio = new javax.swing.JLabel();
        nameAddGastos = new javax.swing.JTextField();
        unidadAddGastos = new javax.swing.JTextField();
        precioAddGastos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        setResizable(false);

        descriptionAddGastos.setColumns(20);
        descriptionAddGastos.setRows(5);
        scroll.setViewportView(descriptionAddGastos);

        accAddGastos.setText("Añadir");
        accAddGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accAddGastosActionPerformed(evt);
            }
        });

        canAddGastos.setText("Cancelar");
        canAddGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canAddGastosActionPerformed(evt);
            }
        });

        addGastosName.setText("Nombre");

        addGastosDescription.setText("Descripción");

        addGastosUnidad.setText("Unidad");

        addGastosPrecio.setText("Precio");

        unidadAddGastos.setText("0");

        precioAddGastos.setText("0.00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(accAddGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(canAddGastos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addGastosName)
                                    .addComponent(addGastosUnidad)
                                    .addComponent(unidadAddGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addGastosPrecio)
                                    .addComponent(precioAddGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameAddGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addGastosDescription)
                                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGastosDescription)
                    .addComponent(addGastosName))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameAddGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addGastosUnidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidadAddGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addGastosPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioAddGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canAddGastos)
                    .addComponent(accAddGastos))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accAddGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accAddGastosActionPerformed
        // TODO add your handling code here:
        if ((nameAddGastos.getText().equals("")) || (descriptionAddGastos.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Se debe especificar un nombre y una descripción.");
        } else if (getPrice() < 0) {
            JOptionPane.showMessageDialog(null, "El precio no puede ser negativo");
        } else if (getUnidades() < 0) {
            JOptionPane.showMessageDialog(null, "Las unidades no pueden ser inferiores a 0");
        } else {
            try {
                String query = " insert into gasto (id, name, description, project, unidad, precio)"
                        + " values (?, ?, ?, ?, ?, ?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = connection.prepareStatement(query);
                preparedStmt.setInt(1, identificador.getId());
                preparedStmt.setString(2, nameAddGastos.getText());
                preparedStmt.setString(3, descriptionAddGastos.getText());
                preparedStmt.setString(4, project);
                preparedStmt.setInt(5, Integer.parseInt(unidadAddGastos.getText()));
                preparedStmt.setFloat(6, Float.parseFloat(precioAddGastos.getText()));

                // execute the preparedstatement
                preparedStmt.execute();
                JOptionPane.showMessageDialog(null, "Se ha añadido el gasto " + nameAddGastos.getText() + " con éxito");
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            Gastos gastos = new Gastos(project, developer);
            gastos.setLocationRelativeTo(null);
            gastos.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_accAddGastosActionPerformed

    private void canAddGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canAddGastosActionPerformed
        // TODO add your handling code here:
        Gastos gastos = new Gastos(project, developer);
        gastos.setLocationRelativeTo(null);
        gastos.setVisible(true);
        dispose();
    }//GEN-LAST:event_canAddGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accAddGastos;
    private javax.swing.JLabel addGastosDescription;
    private javax.swing.JLabel addGastosName;
    private javax.swing.JLabel addGastosPrecio;
    private javax.swing.JLabel addGastosUnidad;
    private javax.swing.JButton canAddGastos;
    private javax.swing.JTextArea descriptionAddGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameAddGastos;
    private javax.swing.JTextField precioAddGastos;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField unidadAddGastos;
    // End of variables declaration//GEN-END:variables

    private float getPrice() {
        return Float.parseFloat(precioAddGastos.getText());
    }

    private int getUnidades() {
        return Integer.parseInt(unidadAddGastos.getText());
    }
}
