/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scm;

import bon.BD;
import java.awt.HeadlessException;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class AddResource extends javax.swing.JFrame {

    /**
     * Creates new form AddResource
     */
    private String project;
    private String resource;
    private String developer2;
    BD bd = new BD();
    Connection connection = bd.conexion();
    private int id;
    private IdentificadorResource identificador;

    public AddResource() {
        initComponents();
    }

    public AddResource(String proy, String re, String dev) {
        project = proy;
        resource = re;
        developer2 = dev;
        initComponents();
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from resource");
            while (rs.next()) {
                id = Integer.parseInt(rs.getString("id"));
            }
            identificador = new IdentificadorResource(id);
        } catch (SQLException e) {
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addResourceName = new javax.swing.JLabel();
        addResourceDescription = new javax.swing.JLabel();
        nameAddResource = new javax.swing.JTextField();
        unidadAddResource = new javax.swing.JTextField();
        addResourceUnidad = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        descriptionAddResource = new javax.swing.JTextArea();
        addResourcePrecio = new javax.swing.JLabel();
        precioAddResource = new javax.swing.JTextField();
        accAddResource = new javax.swing.JButton();
        canAddResource = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scrum master - Añadir recurso");

        addResourceName.setText("Nombre del recurso");

        addResourceDescription.setText("Descripción");

        unidadAddResource.setText("0");

        addResourceUnidad.setText("Unidades");

        descriptionAddResource.setColumns(20);
        descriptionAddResource.setRows(5);
        scroll.setViewportView(descriptionAddResource);

        addResourcePrecio.setText("Precio");

        precioAddResource.setText("0.00");

        accAddResource.setText("Añadir");
        accAddResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accAddResourceActionPerformed(evt);
            }
        });

        canAddResource.setText("Cancelar");
        canAddResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canAddResourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addResourceName)
                    .addComponent(nameAddResource, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addResourceDescription)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accAddResource, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addResourcePrecio)
                    .addComponent(addResourceUnidad)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(precioAddResource, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addComponent(unidadAddResource))
                    .addComponent(canAddResource))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addResourceUnidad)
                        .addGap(3, 3, 3)
                        .addComponent(unidadAddResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addResourcePrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioAddResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accAddResource)
                            .addComponent(canAddResource))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addResourceName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nameAddResource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addResourceDescription)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canAddResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canAddResourceActionPerformed
        // TODO add your handling code here:
        SelectResource sele = new SelectResource(project, developer2);
        sele.setLocationRelativeTo(null);
        sele.setVisible(true);
        dispose();
    }//GEN-LAST:event_canAddResourceActionPerformed

    private void accAddResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accAddResourceActionPerformed
        // TODO add your handling code here:
        if (nameAddResource.getText().equals("") || descriptionAddResource.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Se debe indicar un nombre y una descripción.");
        } else if (getPrice() < 0) {
            JOptionPane.showMessageDialog(null, "El precio no puede ser negativo");
        } else if (getUnidades() < 0) {
            JOptionPane.showMessageDialog(null, "Las unidades no pueden ser inferiores a 0");
        } else {
            try {

                String query = " insert into resource (id, name, description, unidad, project, precio)"
                        + " values (?, ?, ?, ?, ?, ?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = connection.prepareStatement(query);
                preparedStmt.setInt(1, identificador.getId());
                preparedStmt.setString(2, nameAddResource.getText());
                preparedStmt.setString(3, descriptionAddResource.getText());
                preparedStmt.setInt(4, Integer.parseInt(unidadAddResource.getText()));
                preparedStmt.setString(5, project);
                preparedStmt.setFloat(6, Float.parseFloat(precioAddResource.getText()));

                // execute the preparedstatement
                preparedStmt.execute();

            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            SelectResource sele = new SelectResource(project, developer2);
            sele.setLocationRelativeTo(null);
            sele.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_accAddResourceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddResource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accAddResource;
    private javax.swing.JLabel addResourceDescription;
    private javax.swing.JLabel addResourceName;
    private javax.swing.JLabel addResourcePrecio;
    private javax.swing.JLabel addResourceUnidad;
    private javax.swing.JButton canAddResource;
    private javax.swing.JTextArea descriptionAddResource;
    private javax.swing.JTextField nameAddResource;
    private javax.swing.JTextField precioAddResource;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField unidadAddResource;
    // End of variables declaration//GEN-END:variables

    private float getPrice() {
        return Float.parseFloat(precioAddResource.getText());
    }

    private int getUnidades() {
        return Integer.parseInt(unidadAddResource.getText());
    }
}
