/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scm;

import bon.BD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class EstimarIngresos extends javax.swing.JFrame {

    /**
     * Creates new form EstimarIngresos
     */
    private String project;
    BD bd = new BD();
    private String developer2;
    Connection connection = bd.conexion();
    private int id;
    private IdentificadorIngreso identificador;

    public EstimarIngresos() {
        initComponents();
    }

    public EstimarIngresos(String proy, String dev) {
        initComponents();
        project = proy;
        developer2 = dev;
        jLabel1.setText("<Html> Proyecto"+project+"<br> Ventana: Añadir Ingresos</Html>");
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from ingreso");
            while (rs.next()) {
                id = Integer.parseInt(rs.getString("id"));
            }
            identificador = new IdentificadorIngreso(id);
        } catch (SQLException e) {
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estimarIngresosName = new javax.swing.JLabel();
        estimarIngresosDescription = new javax.swing.JLabel();
        estimarIngresosUnidad = new javax.swing.JLabel();
        estimarIngresosPrecio = new javax.swing.JLabel();
        nameEstimarIngresos = new javax.swing.JTextField();
        unidadEstimarIngresos = new javax.swing.JTextField();
        precioEstimarIngresos = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        descriptionEstimarIngresos = new javax.swing.JTextArea();
        accEstimarIngresos = new javax.swing.JButton();
        canEstimarIngresos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        setResizable(false);

        estimarIngresosName.setText("Nombre");

        estimarIngresosDescription.setText("Descripción");

        estimarIngresosUnidad.setText("Unidad");

        estimarIngresosPrecio.setText("Precio");

        unidadEstimarIngresos.setText("0");

        precioEstimarIngresos.setText("0.00");

        descriptionEstimarIngresos.setColumns(20);
        descriptionEstimarIngresos.setRows(5);
        scroll.setViewportView(descriptionEstimarIngresos);

        accEstimarIngresos.setText("Añadir");
        accEstimarIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accEstimarIngresosActionPerformed(evt);
            }
        });

        canEstimarIngresos.setText("Cancelar");
        canEstimarIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canEstimarIngresosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estimarIngresosPrecio)
                        .addGap(287, 287, 287))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimarIngresosName)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameEstimarIngresos)
                                .addComponent(unidadEstimarIngresos)
                                .addComponent(precioEstimarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(estimarIngresosUnidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(canEstimarIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accEstimarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(estimarIngresosDescription)
                                .addGap(65, 65, 65))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimarIngresosName)
                    .addComponent(estimarIngresosDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameEstimarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(estimarIngresosUnidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidadEstimarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(estimarIngresosPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioEstimarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(accEstimarIngresos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canEstimarIngresos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accEstimarIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accEstimarIngresosActionPerformed
        // TODO add your handling code here:
        if (nameEstimarIngresos.getText().equals("") || descriptionEstimarIngresos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Se debe indicar un nombre y una descripción.");
        } else if (getPrice() < 0) {
            JOptionPane.showMessageDialog(null, "El precio no puede ser negativo");
        } else if (getUnidades() < 0) {
            JOptionPane.showMessageDialog(null, "Las unidades no pueden ser inferiores a 0");
        } else {
            try {

                String query = " insert into ingreso (id, name, description, project, unidad, precio)"
                        + " values (?, ?, ?, ?, ?, ?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = connection.prepareStatement(query);
                preparedStmt.setInt(1, identificador.getId());
                preparedStmt.setString(2, nameEstimarIngresos.getText());
                preparedStmt.setString(3, descriptionEstimarIngresos.getText());
                preparedStmt.setString(4, project);
                preparedStmt.setInt(5, Integer.parseInt(unidadEstimarIngresos.getText()));
                preparedStmt.setFloat(6, Float.parseFloat(precioEstimarIngresos.getText()));

                // execute the preparedstatement
                preparedStmt.execute();
                JOptionPane.showMessageDialog(null, "Se ha añadido el ingreso "+nameEstimarIngresos.getText() + " con éxito");
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            Ingreso ingreso = new Ingreso(project, developer2);
            ingreso.setLocationRelativeTo(null);
            ingreso.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_accEstimarIngresosActionPerformed

    private void canEstimarIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canEstimarIngresosActionPerformed
        // TODO add your handling code here:
        Ingreso ingreso = new Ingreso(project, developer2);
        ingreso.setLocationRelativeTo(null);
        ingreso.setVisible(true);
        dispose();
    }//GEN-LAST:event_canEstimarIngresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstimarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstimarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstimarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstimarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstimarIngresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accEstimarIngresos;
    private javax.swing.JButton canEstimarIngresos;
    private javax.swing.JTextArea descriptionEstimarIngresos;
    private javax.swing.JLabel estimarIngresosDescription;
    private javax.swing.JLabel estimarIngresosName;
    private javax.swing.JLabel estimarIngresosPrecio;
    private javax.swing.JLabel estimarIngresosUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameEstimarIngresos;
    private javax.swing.JTextField precioEstimarIngresos;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField unidadEstimarIngresos;
    // End of variables declaration//GEN-END:variables

    private float getPrice() {
        return Float.parseFloat(precioEstimarIngresos.getText());
    }

    private int getUnidades() {
        return Integer.parseInt(unidadEstimarIngresos.getText());
    }
}
