/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scm;

import bon.BD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author yonay
 */
public class Gastos extends javax.swing.JFrame {

    /**
     * Creates new form Gastos
     */
    private String project;
    BD bd = new BD();
    private float precio=0;
    private float mul=0;
    private float recursos;
    private String developer2;
    Connection connection = bd.conexion();
    public Gastos() {
        initComponents();
    }
    public Gastos(String proy,String dev){
        initComponents();
        project=proy;
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from resource");
            while(rs.next()){
                
                recursos=Float.parseFloat(rs.getString("precio")) * Float.parseFloat(rs.getString("unidad"));
            }
        }catch(SQLException e){
            System.out.println("No se pudo acceder");
        }
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from gasto");
            while(rs.next()){
                
                mul=Float.parseFloat(rs.getString("precio")) * Float.parseFloat(rs.getString("unidad"));
                precio+=mul;
            }
            precio+=recursos;
            totalGastos.setText(String.valueOf(precio) + " €");
        }catch(SQLException e){
            System.out.println("No se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gastosTotal = new javax.swing.JLabel();
        totalGastos = new javax.swing.JLabel();
        accGastos = new javax.swing.JButton();
        canGastos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scrum master - Gastos");

        gastosTotal.setText("Gastos Totales");

        totalGastos.setText("jLabel2");

        accGastos.setText("Añadir");
        accGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accGastosActionPerformed(evt);
            }
        });

        canGastos.setText("Cancelar");
        canGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canGastosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(canGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gastosTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(totalGastos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(gastosTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalGastos)
                .addGap(49, 49, 49)
                .addComponent(accGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canGastos)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accGastosActionPerformed
        // TODO add your handling code here:
        AddGastos add = new AddGastos(project,developer2);
        add.setLocationRelativeTo(null);
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_accGastosActionPerformed

    private void canGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canGastosActionPerformed
        // TODO add your handling code here:
        RealizarStimacion realizarStimacion = new RealizarStimacion(project,developer2);
        realizarStimacion.setLocationRelativeTo(null);
        realizarStimacion.setVisible(true);
        dispose();
    }//GEN-LAST:event_canGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accGastos;
    private javax.swing.JButton canGastos;
    private javax.swing.JLabel gastosTotal;
    private javax.swing.JLabel totalGastos;
    // End of variables declaration//GEN-END:variables
}
