/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scm;

import bon.BD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author yonay
 */
public class Inform extends javax.swing.JFrame {

    /**
     * Creates new form Inform
     */
    private String project;
    private String inform;
    private String developer;
    BD bd = new BD();
    Connection connection = bd.conexion();
    public Inform() {
        initComponents();
    }
    public Inform(String proj,String selec,String dev){
        initComponents();
        developer=dev;
        project=proj;
        inform=selec;
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from informeriesgo");
            
            while(rs.next()){
                if((rs.getString("project").equals(project)) && (inform.equals(rs.getString("tittle")))){
                    description.setText(rs.getString("description"));
                    developerInform.setText(rs.getString("develop"));
                    titleInform.setText("<Html>"+proj+" /Informe /" +rs.getString("tittle") +"</Html>");
                }
            }
            }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleInform = new javax.swing.JLabel();
        informDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        canInform = new javax.swing.JButton();
        developerInform = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        titleInform.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleInform.setText("jLabel1");
        getContentPane().add(titleInform);

        informDescription.setText("Descripción");
        getContentPane().add(informDescription);

        description.setEditable(false);
        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);

        canInform.setText("Cancelar");
        canInform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canInformActionPerformed(evt);
            }
        });
        getContentPane().add(canInform);

        developerInform.setText("jLabel4");
        getContentPane().add(developerInform);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canInformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canInformActionPerformed
        // TODO add your handling code here:
        SeleccionarInforme selecI = new SeleccionarInforme(project,developer);
        selecI.setLocationRelativeTo(null);
        selecI.setVisible(true);
        dispose();
    }//GEN-LAST:event_canInformActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canInform;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel developerInform;
    private javax.swing.JLabel informDescription;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleInform;
    // End of variables declaration//GEN-END:variables
}
