/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scm;

/**
 *
 * @author yonay
 */
public class RealizarStimacion extends javax.swing.JFrame {

    /**
     * Creates new form RealizarStimacion
     */
    private String project;
    private String develop;
    public RealizarStimacion() {
        initComponents();
    }
    
    public RealizarStimacion(String proy,String dev){
        initComponents();
        develop=dev;
        project=proy;
        jLabel1.setText("<Html>"+project+"/RealizarEstimación</Html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasksRealizarEstimar = new javax.swing.JButton();
        gastosRealizarEstimar = new javax.swing.JButton();
        ingresosRealizarEstimar = new javax.swing.JButton();
        canRealizarEstimar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");

        tasksRealizarEstimar.setText("Estimar duracion tareas");
        tasksRealizarEstimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksRealizarEstimarActionPerformed(evt);
            }
        });

        gastosRealizarEstimar.setText("Estimar gastos");
        gastosRealizarEstimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosRealizarEstimarActionPerformed(evt);
            }
        });

        ingresosRealizarEstimar.setText("Estimar ingresos");
        ingresosRealizarEstimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosRealizarEstimarActionPerformed(evt);
            }
        });

        canRealizarEstimar.setText("Cancelar");
        canRealizarEstimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canRealizarEstimarActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canRealizarEstimar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresosRealizarEstimar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gastosRealizarEstimar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasksRealizarEstimar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(tasksRealizarEstimar)
                .addGap(18, 18, 18)
                .addComponent(gastosRealizarEstimar)
                .addGap(18, 18, 18)
                .addComponent(ingresosRealizarEstimar)
                .addGap(18, 18, 18)
                .addComponent(canRealizarEstimar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tasksRealizarEstimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksRealizarEstimarActionPerformed
        // TODO add your handling code here:
        SeleccionarTareaParaEstimar seleccionarTareaParaEstimar = new SeleccionarTareaParaEstimar(project,develop);
        seleccionarTareaParaEstimar.setLocationRelativeTo(null);
        seleccionarTareaParaEstimar.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_tasksRealizarEstimarActionPerformed

    private void gastosRealizarEstimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosRealizarEstimarActionPerformed
        // TODO add your handling code here:
        Gastos gastos = new Gastos(project,develop);
        gastos.setLocationRelativeTo(null);
        gastos.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_gastosRealizarEstimarActionPerformed

    private void ingresosRealizarEstimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosRealizarEstimarActionPerformed
        // TODO add your handling code here:
        Ingreso ingreso = new Ingreso(project,develop);
        ingreso.setLocationRelativeTo(null);
        ingreso.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ingresosRealizarEstimarActionPerformed

    private void canRealizarEstimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canRealizarEstimarActionPerformed
        // TODO add your handling code here:
        Gestion gestion = new Gestion(project,develop);
        gestion.setLocationRelativeTo(null);
        gestion.setVisible(true);
        dispose();
    }//GEN-LAST:event_canRealizarEstimarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarStimacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarStimacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarStimacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarStimacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarStimacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canRealizarEstimar;
    private javax.swing.JButton gastosRealizarEstimar;
    private javax.swing.JButton ingresosRealizarEstimar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tasksRealizarEstimar;
    // End of variables declaration//GEN-END:variables
}
