package scm;

import bon.BD;
import bon.Login;
import developer.Developer;
import developer.Task;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yonay
 */
public class ScrumMaster extends javax.swing.JFrame {

    /**
     * Creates new form ScrumMaster
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    private String develop;
    private List<String> lista;
    private List<String> listaFinal;
    public ScrumMaster() {
        initComponents();
    }
    public ScrumMaster(String developer){
        initComponents();
        lista = new ArrayList<>();
        listaFinal = new ArrayList<>();
        develop=developer;
        
        jLabel1.setText("<Html>Logueado como: <br>"+develop+"</Html>");
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from projects");
            while(rs.next()){
                lista.add(rs.getString("name"));
            }
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
        for (String project : lista) {
            Task task = new Task(project,develop);
            if(task.estaVacio()){
                listaFinal.add(project + "-");
            }else{
                listaFinal.add(project + "*");
            }
        }
        for (String project : listaFinal) {
            selectorScrumMaster.add(project);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gestionScrumMaster = new javax.swing.JButton();
        workScrumMaster = new javax.swing.JButton();
        selectorScrumMaster = new java.awt.Choice();
        scrumMasterProjects = new javax.swing.JLabel();
        logoutScrumMaster = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");

        gestionScrumMaster.setText("Gestion");
        gestionScrumMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionScrumMasterActionPerformed(evt);
            }
        });

        workScrumMaster.setText("Trabajar");
        workScrumMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workScrumMasterActionPerformed(evt);
            }
        });

        scrumMasterProjects.setText("Bon Hiato - Project Selection");

        logoutScrumMaster.setText("Log Out");
        logoutScrumMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutScrumMasterActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("* Tienes tareas");

        jLabel3.setText("- No tienes tareas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutScrumMaster))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrumMasterProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(selectorScrumMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gestionScrumMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(workScrumMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutScrumMaster)
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addComponent(scrumMasterProjects)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectorScrumMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gestionScrumMaster))
                .addGap(11, 11, 11)
                .addComponent(workScrumMaster)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workScrumMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workScrumMasterActionPerformed
        // TODO add your handling code here:
        String choice=selectorScrumMaster.getSelectedItem();
        String choice2=choice.substring(0,choice.length()-1);
        Task task = new Task(choice2,develop); 
        if(task.estaVacio()){
            JOptionPane.showMessageDialog(null,"No tienes tareas asignadas en este proyecto");
        }else{
            task.tittle(choice2);
            task.setLocationRelativeTo(null);
            task.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_workScrumMasterActionPerformed

    private void gestionScrumMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionScrumMasterActionPerformed
        // TODO add your handling code here:
        String choice=selectorScrumMaster.getSelectedItem();
        String choice2=choice.substring(0,choice.length()-1);
        Gestion gestion = new Gestion(choice2,develop);
        gestion.setLocationRelativeTo(null);
        gestion.setVisible(true);
        dispose();
    }//GEN-LAST:event_gestionScrumMasterActionPerformed

    private void logoutScrumMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutScrumMasterActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutScrumMasterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScrumMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScrumMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScrumMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScrumMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrumMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gestionScrumMaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutScrumMaster;
    private javax.swing.JLabel scrumMasterProjects;
    private java.awt.Choice selectorScrumMaster;
    private javax.swing.JButton workScrumMaster;
    // End of variables declaration//GEN-END:variables
}
