/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package scm;

import bon.BD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class SeleccionarTareaParaEstimar extends javax.swing.JFrame {

    /** Creates new form SeleccionarTareaParaEstimar */
    BD bd = new BD();
    Connection connection = bd.conexion();
    public String proy;
    List<String> tareas = new ArrayList<>();
    private String developer2;
    
    public SeleccionarTareaParaEstimar() {
        initComponents();
    }

    public SeleccionarTareaParaEstimar(String project,String dev){
        initComponents();
        proy= project;
        developer2=dev;
        selecTareaLab.setText("<Html>"+proy+"/SeleccionarTareas</Html>");
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from task");
            
            while(rs.next()){
                
                if(rs.getString("Projects").equals(proy)){
                    tareas.add(rs.getString("name"));
                }
            }
            if(tareas.size()>0){
                String[] mylist = new String[tareas.size()];
                mylist = tareas.toArray(mylist);
                tasksListSelecTarea.setListData(mylist);
            }
            
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecTareaLab = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tasksListSelecTarea = new javax.swing.JList<>();
        accSelecTarea = new javax.swing.JButton();
        canSelecTarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");

        selecTareaLab.setText("Proyecto Actual");

        scroll.setViewportView(tasksListSelecTarea);

        accSelecTarea.setText("Estimar");
        accSelecTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accSelecTareaActionPerformed(evt);
            }
        });

        canSelecTarea.setText("Cancelar");
        canSelecTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canSelecTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(canSelecTarea))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(accSelecTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selecTareaLab, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(selecTareaLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(accSelecTarea))
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(canSelecTarea)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accSelecTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accSelecTareaActionPerformed
        // TODO add your handling code here:
        String select = tasksListSelecTarea.getSelectedValue();
        if(select == null){
            JOptionPane.showMessageDialog(null, "Seleccione una tarea para estimar.");
        }else{
            EstimarTarea estimarTarea = new EstimarTarea(proy,select,developer2);
            estimarTarea.setLocationRelativeTo(null);
            estimarTarea.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_accSelecTareaActionPerformed

    private void canSelecTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canSelecTareaActionPerformed
        // TODO add your handling code here:
        RealizarStimacion re = new RealizarStimacion(proy,developer2);
        re.setLocationRelativeTo(null);
        re.setVisible(true);
        dispose();
    }//GEN-LAST:event_canSelecTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTareaParaEstimar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTareaParaEstimar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTareaParaEstimar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarTareaParaEstimar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarTareaParaEstimar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accSelecTarea;
    private javax.swing.JButton canSelecTarea;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel selecTareaLab;
    private javax.swing.JList<String> tasksListSelecTarea;
    // End of variables declaration//GEN-END:variables

}
