/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scm;

import bon.BD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class SelectResource extends javax.swing.JFrame {

    /**
     * Creates new form SelectResource
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    public String project;
    private String developer2;

    List<String> re = new ArrayList<>();

    public SelectResource() {
        initComponents();
    }

    public SelectResource(String proj, String dev) {
        initComponents();
        project = proj;
        developer2 = dev;
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from resource");
            while (rs.next()) {
                System.out.println(rs.getString("project"));
                System.out.println(project);

                if (rs.getString("project").equals(project)) {
                    re.add(rs.getString("name"));
                }
            }
            if (re.size() > 0) {
                String[] mylist = new String[re.size()];
                mylist = re.toArray(mylist);
                resourcesListSelecResources.setListData(mylist);
            }

        } catch (SQLException e) {
            System.out.println("no se pudo acceder");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        scroll = new javax.swing.JScrollPane();
        resourcesListSelecResources = new javax.swing.JList<>();
        selecResourcesLab = new javax.swing.JLabel();
        addSelecResources = new javax.swing.JButton();
        remSelecResources = new javax.swing.JButton();
        canSelecResources = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scrum master -  Recursos");

        scroll.setViewportView(resourcesListSelecResources);

        selecResourcesLab.setText("Recursos del Proyecto");

        addSelecResources.setText("Añadir");
        addSelecResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSelecResourcesActionPerformed(evt);
            }
        });

        remSelecResources.setText("Eliminar");
        remSelecResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remSelecResourcesActionPerformed(evt);
            }
        });

        canSelecResources.setText("Cancelar");
        canSelecResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canSelecResourcesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remSelecResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSelecResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(selecResourcesLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(canSelecResources)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(selecResourcesLab)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(addSelecResources)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(remSelecResources)))
                .addGap(26, 26, 26)
                .addComponent(canSelecResources)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canSelecResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canSelecResourcesActionPerformed
        // TODO add your handling code here:
        Gestion gestion = new Gestion(project, developer2);
        gestion.setLocationRelativeTo(null);
        gestion.setVisible(true);
        dispose();
    }//GEN-LAST:event_canSelecResourcesActionPerformed

    private void addSelecResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSelecResourcesActionPerformed
        // TODO add your handling code here:
        String resources = resourcesListSelecResources.getSelectedValue();

        AddResource addResource = new AddResource(project, resources, developer2);
        addResource.setLocationRelativeTo(null);
        addResource.setVisible(true);
        dispose();


    }//GEN-LAST:event_addSelecResourcesActionPerformed

    private void remSelecResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remSelecResourcesActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar el recurso?", "Alerta", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            if (resourcesListSelecResources.getSelectedValue() != null) {

                try {
                    String query = " DELETE FROM resource WHERE name = ?";

                    PreparedStatement preparedStmt = connection.prepareStatement(query);
                    preparedStmt.setString(1, resourcesListSelecResources.getSelectedValue());
                    preparedStmt.execute();
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                SelectResource select = new SelectResource(project, developer2);
                select.setLocationRelativeTo(null);
                select.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un recurso");
            }
        }
    }//GEN-LAST:event_remSelecResourcesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectResource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSelecResources;
    private javax.swing.JButton canSelecResources;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton remSelecResources;
    private javax.swing.JList<String> resourcesListSelecResources;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel selecResourcesLab;
    // End of variables declaration//GEN-END:variables
}
