package developer;

import bon.BD;
import bon.Login;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yonay
 */
public class Developer extends javax.swing.JFrame {

    /**
     * Creates new form Developer
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    private String develop;
    public Developer() {
        initComponents();
    }
    
    public Developer(String develop){
        initComponents();
        this.develop=develop;
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from projects");
            while(rs.next()){
                projectSelectorDeveloper.add(rs.getString("name"));
            }
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        developerTitle = new javax.swing.JLabel();
        projectSelectorDeveloper = new java.awt.Choice();
        selectedDeveloper = new javax.swing.JButton();
        logoutDeveloper = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Developer");

        developerTitle.setText("Bon Hiato-Project Selection");

        selectedDeveloper.setText("Seleccionar");
        selectedDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedDeveloperActionPerformed(evt);
            }
        });

        logoutDeveloper.setText("LogOut");
        logoutDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutDeveloperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectSelectorDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(developerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutDeveloper)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(selectedDeveloper)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(developerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutDeveloper)))
                .addGap(47, 47, 47)
                .addComponent(projectSelectorDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(selectedDeveloper)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectedDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedDeveloperActionPerformed
        // TODO add your handling code here:
        String choice=projectSelectorDeveloper.getSelectedItem();
        Task task = new Task(choice,develop);

        if(task.estaVacio()){
            JOptionPane.showMessageDialog(null,"No tienes tareas asignadas en este proyecto");
        }else{
            task.tittle(choice);
            task.setLocationRelativeTo(null);
            task.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_selectedDeveloperActionPerformed

    private void logoutDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutDeveloperActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "¿Seguro que desea desconectarse?", "Alerta", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutDeveloperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Developer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developerTitle;
    private javax.swing.JButton logoutDeveloper;
    private java.awt.Choice projectSelectorDeveloper;
    private javax.swing.JButton selectedDeveloper;
    // End of variables declaration//GEN-END:variables
}
