package developer;

import bon.BD;
import bon.Login;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yonay
 */
public class Developer extends javax.swing.JFrame {

    /**
     * Creates new form Developer
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    private String develop;
    private List<String> projects = new ArrayList<String>();

    public Developer() {
        initComponents();
    }

    public Developer(String deve) {
        initComponents();
        this.develop = deve;
        jLabel1.setText("<Html>Logueado como: <br>" + develop + "</Html>");
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from projects");
            while (rs.next()) {
                projects.add(rs.getString("name"));

            }
        } catch (SQLException e) {
            System.out.println("no se pudo acceder");
        }
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from task");
            while (rs.next()) {
                for (String project : projects) {
                    if (rs.getString("Projects").equals(project) && rs.getString("develop").equals(develop)) {
                        projectSelectorDeveloper.add(rs.getString("Projects"));
                    }
                }
            }
        } catch (SQLException e) {
            System.out.println("no se pudo acceder");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        developerTitle = new javax.swing.JLabel();
        projectSelectorDeveloper = new java.awt.Choice();
        selectedDeveloper = new javax.swing.JButton();
        logoutDeveloper = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        developerTitle.setText("Bon Hiato-Project Selection");
        getContentPane().add(developerTitle);
        getContentPane().add(projectSelectorDeveloper);

        selectedDeveloper.setText("Seleccionar");
        selectedDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedDeveloperActionPerformed(evt);
            }
        });
        getContentPane().add(selectedDeveloper);

        logoutDeveloper.setText("LogOut");
        logoutDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutDeveloperActionPerformed(evt);
            }
        });
        getContentPane().add(logoutDeveloper);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectedDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedDeveloperActionPerformed
        // TODO add your handling code here:
        String choice = projectSelectorDeveloper.getSelectedItem();
        Task task = new Task(choice, develop);

        if (task.estaVacio()) {
            JOptionPane.showMessageDialog(null, "No tienes tareas asignadas en este proyecto");
        } else {
            task.tittle(choice);
            task.setLocationRelativeTo(null);
            task.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_selectedDeveloperActionPerformed

    private void logoutDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutDeveloperActionPerformed
        // TODO add your handling code here:
        int dialogButton
                = JOptionPane.showConfirmDialog(null, "¿Desea salir de la cuenta actual?", "Aviso!", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutDeveloperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Developer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developerTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutDeveloper;
    private java.awt.Choice projectSelectorDeveloper;
    private javax.swing.JButton selectedDeveloper;
    // End of variables declaration//GEN-END:variables
}
