/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package developer;

import bon.BD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author yonay
 */
public class UpdateTask extends javax.swing.JFrame {

    /**
     * Creates new form UpdateTask
     */
    BD bd = new BD();
    Connection connection = bd.conexion();
    public String taskproject;
    public String projectname;
    public String developer;
    public String idSprint;
    public UpdateTask() {
        initComponents();
    }
    public UpdateTask(String taskname,String projectName,String develop){
        
        initComponents();
        
        developer=develop;
        taskproject=taskname;
        this.projectname=projectName;
        stateUpdate.addItem("0 - sin empezar");
        stateUpdate.addItem("1 - desarrollo");
        stateUpdate.addItem("2 - finalizada");
        stateUpdate.addItem("3 - bloqueada");
        title.setText("<Html>"+projectname+"/UpdateTask</Html>");
        try{
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("select * from task");
            
            while(rs.next()){
                if(rs.getString("name").equals(taskname) && rs.getString("Projects").equals(this.projectname)){
                    taskNameUpdate.setText(taskname);
                    durationUpdate.setText(rs.getString("duration"));
                    descriptionUpdate.setText(rs.getString("description"));
                    priorityUpdate.setText(rs.getString("priority"));
                    logHoursUpdate.setText(rs.getString("hours"));
                    stateUpdate.setSelectedIndex(Integer.parseInt(rs.getString("state")));
                    taskLab.setText(rs.getString("Projects"));
                    idLab.setText(rs.getString("id"));
                    idSprint=rs.getString("sprint");
                }
            }
            
            
        }catch(SQLException e){
            System.out.println("no se pudo acceder");
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskNameLab = new javax.swing.JLabel();
        taskNameUpdate = new javax.swing.JLabel();
        descriptionLab = new javax.swing.JLabel();
        durationLab = new javax.swing.JLabel();
        durationUpdate = new javax.swing.JLabel();
        priorityLab = new javax.swing.JLabel();
        priorityUpdate = new javax.swing.JLabel();
        logHoursLab = new javax.swing.JLabel();
        stateLab = new javax.swing.JLabel();
        logHoursUpdate = new javax.swing.JTextField();
        accUpdate = new javax.swing.JButton();
        canUpdate = new javax.swing.JButton();
        taskLab = new javax.swing.JLabel();
        idLab = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        descriptionUpdate = new javax.swing.JTextArea();
        stateUpdate = new javax.swing.JComboBox<String>();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bon-Hiato");

        taskNameLab.setText("Nombre de la tarea");

        taskNameUpdate.setText("Name of the task");

        descriptionLab.setText("Descripción");

        durationLab.setText("Duración");

        durationUpdate.setText("Duration of the task");

        priorityLab.setText("Prioridad");

        priorityUpdate.setText("Priority of the task");

        logHoursLab.setText("Horas trabajadas");

        stateLab.setText("Estado (0-3)");

        accUpdate.setText("Modificar");
        accUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accUpdateActionPerformed(evt);
            }
        });

        canUpdate.setText("Cancelar");
        canUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canUpdateActionPerformed(evt);
            }
        });

        taskLab.setText("Tarea");

        idLab.setText("Id de la tarea");

        descriptionUpdate.setEditable(false);
        descriptionUpdate.setColumns(20);
        descriptionUpdate.setRows(5);
        scroll.setViewportView(descriptionUpdate);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taskNameLab)
                                    .addComponent(stateLab))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durationUpdate)
                                    .addComponent(durationLab)
                                    .addComponent(priorityLab)
                                    .addComponent(priorityUpdate)
                                    .addComponent(idLab)))
                            .addComponent(stateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLab)
                            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taskNameUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accUpdate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logHoursLab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logHoursUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addComponent(canUpdate))
                    .addComponent(taskLab)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskLab)
                    .addComponent(idLab)
                    .addComponent(descriptionLab))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskNameLab)
                            .addComponent(durationLab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskNameUpdate)
                            .addComponent(durationUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priorityLab)
                            .addComponent(logHoursLab))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priorityUpdate)
                            .addComponent(logHoursUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(stateLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accUpdate)
                    .addComponent(canUpdate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canUpdateActionPerformed
        // TODO add your handling code here:
        Task task = new Task(projectname,developer);
        task.tittle(projectname);
        task.setLocationRelativeTo(null);
        task.setVisible(true);
        dispose();
    }//GEN-LAST:event_canUpdateActionPerformed
    private int getStateUpdate(){
        return stateUpdate.getSelectedIndex();
    }
    private void accUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accUpdateActionPerformed
        // TODO add your handling code here:
        
            try {
                
                String val1 = taskNameUpdate.getText(); 
                String val2 = descriptionUpdate.getText(); 
                String val3 = String.valueOf(stateUpdate.getSelectedIndex()); 
                String val4 = priorityUpdate.getText(); 
                String val5 = durationUpdate.getText(); 
                String val6 = logHoursUpdate.getText();
                String val7 = taskLab.getText();
                String val8 = idLab.getText();

            String sql = "UPDATE task set Projects='"+val7+"',name='"
            +val1+"',duration='"+val5+"',priority='"
            +val4+"',description='"
            +val2+"',state='"
            +val3+"',hours='"
            +val6+"',develop='"
            +developer+"',sprint='"
            +idSprint+"' where id='"
            +val8+"'";
        PreparedStatement pst=connection.prepareStatement(sql);
        pst.execute();
           JOptionPane.showMessageDialog(null, "La tarea"+taskNameUpdate.getText()+" ha sido modificada con éxito");     
        } catch (SQLException | HeadlessException e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
        Task task2 = new Task(projectname,developer);
        task2.tittle(projectname);
        task2.setLocationRelativeTo(null);
        task2.setVisible(true);
        dispose();
        
           
    }//GEN-LAST:event_accUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accUpdate;
    private javax.swing.JButton canUpdate;
    private javax.swing.JLabel descriptionLab;
    private javax.swing.JTextArea descriptionUpdate;
    private javax.swing.JLabel durationLab;
    private javax.swing.JLabel durationUpdate;
    private javax.swing.JLabel idLab;
    private javax.swing.JLabel logHoursLab;
    private javax.swing.JTextField logHoursUpdate;
    private javax.swing.JLabel priorityLab;
    private javax.swing.JLabel priorityUpdate;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel stateLab;
    private javax.swing.JComboBox<String> stateUpdate;
    private javax.swing.JLabel taskLab;
    private javax.swing.JLabel taskNameLab;
    private javax.swing.JLabel taskNameUpdate;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
